version: "1"
services:
  mysqldb:
    container_name: OnlineShop
    image: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: OnlineShop
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: test
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234"]
      timeout: 20s
      retries: 10

  springboot-app:
    container_name: spring-shop-online
    image: shop-online.1.0
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    #    environment:
    #      MYSQL_HOST: mysql-shop
    #      MYSQL_DATABASE: myShopDB
    #      MYSQL_USER: root
    #      MYSQL_PASSWORD: 1234
    #      MYSQL_PORT: 33306    # we are in same network so we connect internally.
    depends_on:
      mysqldb:
        condition: service_healthy